version: "3"
services:
    load_balancer:
        build:
            context: ./load_balancer
        ports:
            - "80:80"
        environment:
            - BACKEND_SERVICES=app1:5000 app2:5000 app3:5000
        depends_on:
            - app1
            - app2
            - app3

    app1:
        build:
            context: ./app1
        ports:
            - "5001:5000"

    app2:
        build:
            context: ./app2
        ports:
            - "5002:5000"

    app3:
        build:
            context: ./app3
        ports:
            - "5003:5000"
